CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price BIGINT NOT NULL,
    stock_quantity BIGINT DEFAULT 0,
    CONSTRAINT price_check CHECK (price >= 0),
    CONSTRAINT stock_quantity_check CHECK (stock_quantity >= 0)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    order_date TIMESTAMP DEFAULT current_date,
    status VARCHAR(20) NOT NULL DEFAULT 'ORDERED',
    FOREIGN KEY (member_id) REFERENCES members(id),
    CONSTRAINT status_check CHECK (status IN ('ORDERED', 'CANCELED', 'DELIVERED'))
);

CREATE TABLE order_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    order_price BIGINT NOT NULL,
    quantity BIGINT NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT order_price_check CHECK (order_price >= 0),
    CONSTRAINT quantity_check CHECK (quantity >= 0)
);